### ISSUE TITLE
Error 401 (Unauthorized) on refresh

### ISSUE THREAD

**Issue by yanapoz** [phillbaker/terraform-provider-elasticsearch#208] opened 2021-08-10 08:29 UTC
Hey there,

I'm using the provider with a username and password auth. The first time, it runs perfectly. But when I try to refresh the terraform state it fails with `Error: elastic: Error 401 (Unauthorized)` and `"stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: missing authentication credentials for REST request [/]"` in Elasticsearch. 

Terraform version: 1.0.0
Provider Version: 1.6.2
Elasticsearch Version: 7.12.1
Operation Mode: ECK operator

**Comment by phillbaker** [comment] 2021-08-12 02:46
Hello, can you please include the following:
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by phillbaker** [comment] 2022-01-03 00:36
Hi, following up on this to see if you can provide additional details. I can't reproduce this with `terraform apply && terraform refresh`. If no other details are provided, I'll go ahead and close this issue out.

**Closed** 2022-01-04 14:00 UTC

**Comment by mrsiejas** [comment] 2022-04-29 14:55
@phillbaker how to use provider if no authentication is used (we are limiting access via VPN)?
To run terraform commands we are assuming roles for example with aws provider
```
provider "aws" {
  alias  = "us-east-2"
  region = "us-east-2"

  assume_role {
    role_arn = local.role_arn
  }
}
```

but elasticsearch - with or without the `aws_assume_role_arn` produces same 401 unathorised
```
provider "elasticsearch" {
  url        = "https://vpc-dev-foo.eu-west-1.es.amazonaws.com"
  aws_region = "eu-west-1"
  #  aws_assume_role_arn = local.role_arn
}
```

I can curl the `url` endpoint from my laptop without any authentication and it works.
