### ISSUE TITLE
Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.

### ISSUE THREAD

**Issue by xi3826-spandey** [phillbaker/terraform-provider-elasticsearch#284] opened 2022-06-09 06:28 UTC
Please help me for the below issue, I have tried couple of permutation and combination but couldn't find any solution. 
```
Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.
│
│   with module.opensearch.elasticsearch_index_template.index_template["01-template"],
│   on ../../../../_terraform_modules/xebia/terraform-aws-xebia-elasticsearch-1.0.0/index_template.tf line 1, in resource "elasticsearch_index_template" "index_template":
│    1: resource "elasticsearch_index_template" "index_template" {
│
╵
Releasing state lock. This may take a few moments...
make: *** [apply] Error 1
```
================

using below versions.tf
```
**terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.65"
    }
    elasticsearch = {
      source  = "phillbaker/elasticsearch"
      version = ">= 2.0.0"
    }
  }
}
**
```
@phillbaker

**Comment by phillbaker** [comment] 2022-06-12 23:40
Hello, what steps have you taken so far to debug the issue? The error message is descriptive in this case: the provider cannot reach the configured elasticsearch cluster. 

Please include the following information:
* from where are you running the provider?
* where is the elasticsearch cluster located?
* what is the networking configuration for where the elasticsearch cluster runs and all the networks connecting the location where the provider is running to the cluster?


Note: Issues on this repository are for reporting bugs and feature requests for this provider, not providing support for unique environments. In order to investigate this, a reproducible case may needs to be provided, if that can't be provided, we'll have to close this issue to focus on widely impacting issues.

**Comment by phillbaker** [comment] 2022-06-21 00:39
Closing this issue due to lack of information. Please reopen if further information can be provided.

**Closed by phillbaker** 2022-06-21 00:39 UTC
