### ISSUE TITLE
Error 401 (Unauthorized) for elasticsearch_index_template

### ISSUE THREAD

**Issue by tjbaker** [phillbaker/terraform-provider-elasticsearch#172] opened 2021-05-14 23:05 UTC
I had code like this prior to the latest AWS ES update that used to work:

```
resource "elasticsearch_index_template" "no-can-do" {
  name = "non-production"
  body = <<EOF
{
  "index_patterns": [
    "foo*"
  ],
  "settings": {
    "number_of_replicas": 1,
    "number_of_shards": 1,
    "opendistro.index_state_management.policy_id": "delete_after_1m"
  }
}
EOF
}
```

Now I get this for any elasticsearch_index_template apply

```
Error: elastic: Error 401 (Unauthorized)

  on modules/ism/main.tf line 90, in resource "elasticsearch_index_template" "no-can-do":
  90: resource "elasticsearch_index_template" "no-can-do" {
```

I can apply the same json via kibana "Dev Tools" interface via POST and it works fine

**Comment by phillbaker** [comment] 2021-05-15 19:53
Hello, can you please include the following:
* provider version (and if it changed recently)
* elasticsearch version (and opendistro version if relevant), specifically, what AWS ES versions did you upgrade from and to?
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by tjbaker** [comment] 2021-05-16 11:59
I get the 401 with 1.5.3 and 1.5.6 providers
Am now running AWS ES patch R20210426 

```
GET /

  "version" : {
    "number" : "7.9.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-04-21T04:39:06.845169Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }
```

I'll repost with the verbose logs.

**Comment by ventsislav-georgiev** [comment] 2021-05-17 13:45
I have the same issue with `elasticsearch_index_template` only in the AWS ES service. The `elasticsearch_index` itself has no issues of being created/destroyed. The provisioning code hasn't been changed and since last week it started giving error: `Error 401 (Unauthorized)`.

Service Version: [R20210426](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table)
```json
{
  "name" : "f028312b461f7c8ff71f9b5edc0c19ae",
  "cluster_name" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "cluster_uuid" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-04-21T04:22:10.395481Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Stripped logs:
```
[INFO] Terraform version: 0.13.5
[INFO] Go runtime version: go1.14.7
[INFO] AWS Auth provider used: "SharedCredentialsProvider"
[INFO] Attempting to AssumeRole arn:aws:iam::xxxxxxxxxxxx:role/TerraformStateWriter (SessionName: "xxxxxx@xxxxxxxx.com", ExternalId: "")
[INFO] backend/local: starting Apply operation
Acquiring state lock. This may take a few moments...
[INFO]  plugin.terraform-provider-elasticsearch_v1.5.6: configuring server automatic mTLS
[INFO] backend/local: apply calling Apply
[INFO] terraform: building graph: GraphTypeApply
[INFO]  plugin.terraform-provider-elasticsearch_v1.5.6: configuring server automatic mTLS
elasticsearch_index_template.oi[0]: Creating...
[ERROR] eval: *terraform.EvalApplyPost, err: elastic: Error 401 (Unauthorized)
[ERROR] eval: *terraform.EvalSequence, err: elastic: Error 401 (Unauthorized)

Error: elastic: Error 401 (Unauthorized)
```

**Comment by phillbaker** [comment] 2021-05-18 03:34
Given that this was reproduced with provider versions 1.5.3 and 1.5.6, and was correlated with an upgrade in AWS ES, it seems like the the AWS ES upgrade may be involved. If you have not opened an issues with AWS, please do so and share the results.

**Comment by ventsislav-georgiev** [comment] 2021-05-18 07:20
@phillbaker with a bit more testing the issue is caused by setting:
```json
"settings": {
  "opendistro.index_state_management.policy_id": "delete_after_1m"
}
```

When I remove the `opendistro.index_state_management.policy_id` and `opendistro.index_state_management.rollover_alias` the index_template creates without issues.

**Comment by ventsislav-georgiev** [comment] 2021-05-18 09:30
It seems that Open Distro for Elasticsearch 1.13 has deprecated setting those in the index_template and are now part of the policy it self via ism_template: https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/
<img width="757" alt="image" src="https://user-images.githubusercontent.com/5616486/118627895-c3271400-b7d4-11eb-85d3-07ed644c8017.png">

**Comment by ventsislav-georgiev** [comment] 2021-05-18 10:23
Side note: The `elasticsearch_opendistro_ism_policy_mapping` seems to create the mapping but complete with error code. However with the index_pattern in the policy, this is no longer required as long the order of creation is first the policy and then the index. That way the index is automatically mapped to the policy.

**Comment by phillbaker** [comment] 2021-05-19 02:48
Thanks @ventsislav-georgiev. @tjbaker can you confirm that this also addresses the issue you're seeing? If so, I'll close this issue out.

**Comment by tjbaker** [comment] 2021-05-19 12:13
Yes, I found I needed to move the ism reference from the elasticsearch_index_template to elasticsearch_opendistro_ism_policy

The new code in elasticsearch_opendistro_ism_policy looks something like:

```
resource "elasticsearch_opendistro_ism_policy" "two_weeks" {
  policy_id = "delete_after_2w"
  body      = <<EOF
{
  "policy": {
    "policy_id": "delete_after_2w",
    "description": "Delete index after 2 weeks",
    "schema_version": 1,
    "default_state": "hot",
    "states": [
      {
        "name": "hot",
        "actions": [],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "14d"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ],
    "ism_template": [
      {
        "index_patterns": [
          "delete-me-after-14d"
        ],
        "priority": 0
      }
    ]
  }
}
EOF
}
```

**Comment by phillbaker** [comment] 2021-05-20 00:43
great, i'm going to close this issue then. thanks!

**Closed by phillbaker** 2021-05-20 00:43 UTC

**Comment by thecosmicfrog** [comment] 2021-06-03 12:12
Thanks @ventsislav-georgiev and @tjbaker - that solved the issue for me.

For reference, here is the diff of the changes I had to make:

**main.tf:**
```hcl
[...]

resource "elasticsearch_opendistro_ism_policy" "ism_policy" {
  count = var.enable_retention_policy ? 1 : 0

  policy_id = "retention-policy"
  body = templatefile("${path.module}/templates/retention-policy.json", {
    retention_policy_age = "${var.index_retention_in_days}d"
  })
}

// Not supported anymore - delete this entire resource.
-resource "elasticsearch_index_template" "index_template" {
-  count = var.enable_retention_policy ? 1 : 0
-
-  name = "retention-policy-template"
-  body = jsonencode({
-    index_patterns = var.index_patterns
-    settings = {
-      "opendistro.index_state_management.policy_id" : elasticsearch_opendistro_ism_policy.ism_policy[0].policy_id
-    }
-  })
-}
```

**retention-policy.json:**
```
{
  "policy": {
    "description": "Delete indexes after a certain amount of time.",
    "schema_version": 1,
    "default_state": "current",
    "states": [
      {
        "name": "current",
        "actions": [],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "${retention_policy_age}"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [{
          "delete": {}
        }],
        "transitions": []
      }
    ],
+    "ism_template": [
+      {
+        "index_patterns": [
+          "logs-*",
+        ],
+        "priority": 0
+      }
+    ]
  }
}
```

I'm using a **templatefile** here, but if you're instead using an inline **body**, just add that `"ism_template": []` array with appropriate `"index_patterns"` for your use case.
