### ISSUE TITLE
Support for OpenSearch v2

### ISSUE THREAD

**Issue by sharebear** [phillbaker/terraform-provider-elasticsearch#323] opened 2022-11-10 07:30 UTC
I was previously successfully using the `elasticsearch_ingest_pipeline` resource against OpenSearch v1. After upgrading to v2 I get the following error

> Error: ElasticSearch version 2.3.0 is older than 6.0.0 and is not supported, flavor: 0.

Reading through the information in #268 I am able to set `elasticsearch_version = "7.17.7"` which seems to allow terraform progress.

Is this the recommended way forward for now? Should the provider instead be adding an `opensearch_ingest_pipeline` resource? This is something I could perhaps try and contribute to when I have a little time...

**Comment by phillbaker** [comment] 2022-11-11 13:58
Related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/322 

It is due to this line: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/1ff79e7de71161651f5fe64d73366aab778ea663/es/provider.go#L478. 

We don't have testing support yet for OpenSearch 2.x and it does have breaking api features, so the provider hasn't incorporated support for it. This provider won't include support for opensearch 2.x, that will be done in https://github.com/opensearch-project/terraform-provider-opensearch

**Comment by phillbaker** [comment] 2022-11-25 22:05
Closing as a dupe of https://github.com/phillbaker/terraform-provider-elasticsearch/issues/298

**Closed by phillbaker** 2022-11-25 22:05 UTC
