### ISSUE TITLE
strict_dynamic_mapping_exception with elasticsearch_kibana_object and visualization

### ISSUE THREAD

**Issue by tjbaker** [phillbaker/terraform-provider-elasticsearch#137] opened 2021-01-28 21:47 UTC
AWS ES 7.9 with Kibana 7.9.1

Can't create a visualization

Error: elastic: Error 400 (Bad Request): mapping set to strict, dynamic introduction of [kibanaSavedObjectMeta] within [_doc] is not allowed [type=strict_dynamic_mapping_exception]

```
resource "elasticsearch_kibana_object" "test_visualization" {
  body = <<EOF
[
  {
    "_id": "test_id",
    "_source": {
      "type": "visualization",
      "kibanaSavedObjectMeta": {
        "searchSourceJSON": "valid-stuff-here"
      },
      "title": "Test Visualization",
      "visState": "valid-stuff-here"
    }
  }
]
EOF
}
```

**Comment by phillbaker** [comment] 2021-02-13 23:17
Hi @tjbaker, there's an example in the test suite that runs against 7.9.3 (as of now) successfully: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/116c9ff6da0d481881aa687d3e7bb2e03fdcfcd4/es/resource_elasticsearch_kibana_object_test.go#L245-L264 

Perhaps there's a timing issue here? This also came up in https://github.com/phillbaker/terraform-provider-elasticsearch/issues/87 and there was some discussion there.

**Comment by fdw** [comment] 2021-04-07 14:45
As I struggled with the same problem, I tried out a previous version of the description (v6 in my case), and that worked, even though Kibana is on 7.9. Maybe that works for someone else, too.

**Comment by phillbaker** [comment] 2021-06-01 15:35
Hello, sorry for the confusion here, turns out the tests were not creating the typed kibana index before running and so weren't replicating what happens in a real cluster. I've fixed the tests and documentation to reflect what happens in a cluster in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/3d1a377e7c9d8485c790aab5ef3e187a50ec1068.

Note that the transformation is essentially to have a `type` field and then a nested document under a key of that type. For example, before:
```
"_source": {
  "type": "visualization",
  "title": "Total response time percentiles",
  ...
}
```
after:
```
"_source": {
  "type": "visualization",
  "visualization": {
    "title": "Total response time percentiles",
    ...
  }
}
```

For reference, the mappings allowed in 6.x and 7.x kibana indices are here:
* https://github.com/elastic/kibana/blob/v6.8.16/test/functional/fixtures/es_archiver/mgmt/mappings.json#L249-L276
* https://github.com/elastic/kibana/blob/v7.10.2/test/functional/fixtures/es_archiver/mgmt/mappings.json#L243-L273

I'm going to close this issue for now as the provider was working as intended, however, the documentation was incorrect.

**Closed by phillbaker** 2021-06-01 15:35 UTC
Labels: question
