### ISSUE TITLE
Xpack roles:elastic: Error 400 (Bad Request): request body is required [type=parse_exception]

### ISSUE THREAD

**Issue by andrescolodrero** [phillbaker/terraform-provider-elasticsearch#49] opened 2019-12-18 12:20 UTC
Im having this error:
`Error 400 (Bad Request): request body is required [type=parse_exception]`

On a 7.5.0 Cluster,
with this configuration:
```
resource "elasticsearch_xpack_role" "kibana-admin" {
  role_name = "kibana-admin"
  indices {
    privileges = ["all"]
    field_security  = "*"
    names = ["*"]
  }

  applications {
      application = "kibana-.kibana"
      privileges = ["all"]
      resources = ["*"]

  }
  cluster = ["all"]
}
```

**Comment by phillbaker** [comment] 2019-12-18 14:25
@andrescolodrero what version of the provider are you using?

**Comment by andrescolodrero** [comment] 2019-12-18 14:37
@phillbaker sorry, i forget that detail.
im using latest, v0.10.0.

maybe the client for v7 will need an update?

**Comment by phillbaker** [comment] 2019-12-19 14:36
It looks like there is an issue on 7.5: https://travis-ci.org/phillbaker/terraform-provider-elasticsearch/jobs/626767093#L1400. ESv7.4 and lower don't have issues.

Two potential PRs stand out from [the release notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/release-notes-7.5.0.html)
* https://github.com/elastic/elasticsearch/pull/46361
* https://github.com/elastic/elasticsearch/pull/46275

**Comment by phillbaker** [comment] 2020-01-07 13:54
Looks like the tests pass on v7.5 after fixing some permissions that didn't exist, here's the commit: https://github.com/phillbaker/terraform-provider-elasticsearch/commit/53870647955b08990a4e11e003b66233feb1303b.

Is it possible that the values you used ended up creating invalid JSON when serialized? Did you get this error on a plan or apply? Can you try running the command again with `TF_LOG=INFO` and share the (redacted) output?

**Comment by andrescolodrero** [comment] 2020-01-07 14:32
With same code as before, im getting a new type of error:

Error: Body Error : 

  on roles.tf line 48, in resource "elasticsearch_xpack_role" "arion-kibana-editor":
  48: resource "elasticsearch_xpack_role" "arion-kibana-editor" {


i removed the line:
    field_security  = "*"

in code is "schema.TypeString",
but on my JSON test is:
"field_security": {
          "except": [],
          "grant": [
            "*"
          ]

**Comment by phillbaker** [comment] 2020-01-08 03:41
Hm, I've been able to reproduce that: https://travis-ci.org/phillbaker/terraform-provider-elasticsearch/jobs/634034936#L1231. It comes from: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/53870647955b08990a4e11e003b66233feb1303b/resource_elasticsearch_xpack_role.go#L244-L248

So, the request isn't even being sent, seems like a bug in this provider. Thanks for the additional details.

**Comment by phillbaker** [comment] 2020-01-20 20:13
@andrescolodrero an update on my side: fixing this will likely require changing the type of the field_security attribute. However, I did want to point out, that from the ES docs:
> The absence of field_security in a role is equivalent to * access. 

So there's no need to specify `field_security": {"except": [],"grant": ["*"]`, that's the default.

**Comment by phillbaker** [comment] 2020-03-21 15:28
I believe this was fixed as an outcome of https://github.com/phillbaker/terraform-provider-elasticsearch/pull/59. @andrescolodrero can you try v1.0.0 to see if that fixes the issue?

**Comment by phillbaker** [comment] 2020-03-29 16:09
Going to close this for now, please re-open if this continues to be an issues.

**Closed by phillbaker** 2020-03-29 16:09 UTC
Labels: bug
