### ISSUE TITLE
Error: Unsupported Argument "name" in elasticsearch_xpack_watch

### ISSUE THREAD

**Issue by Siddhant-Tiwari** [phillbaker/terraform-provider-elasticsearch#117] opened 2020-12-02 23:22 UTC
I am configure without the name argument but if I am trying to create a watch with a name, I get this:

**Error: Unsupported argument

  on goanywhere_watcher_pipeline.tf line 2, in resource "elasticsearch_xpack_watch" "GoAnywhereftp-error-watch":
   2:   name = "GoAnywhereftp-error-watch"

An argument named "name" is not expected here.**

**Comment by phillbaker** [comment] 2020-12-05 17:42
Hello, can you please include the following:
* terraform version
* provider version
* redacted version of the terraform resource configuration

**Comment by Siddhant-Tiwari** [comment] 2020-12-08 02:05
Hi Phil,

-  Terraform v0.13.5
-  Provider Version "1.5.0"

Had a quick look at the code, there is no name in the watch schema. Just the watch_id and body:

![IMG-20200304-WA0013](https://user-images.githubusercontent.com/5431001/101429004-bf11e300-3966-11eb-8024-9f38bbe24aac.jpg)

**Comment by phillbaker** [comment] 2020-12-08 02:26
@Siddhant-Tiwari can you please include a redacted version of the terraform resource configuration (ie how you're configuring the elasticsearch_xpack_watch).

**Comment by Siddhant-Tiwari** [comment] 2020-12-08 02:46
Here you go: 
resource "elasticsearch_xpack_watch" "watch_1" {
  watch_id = "watch_1"
  body = <<EOF
{
  "trigger": {
    "schedule": {
      "interval": "10m"
    }
  },
  "input" : {
    "search" : {
      "request" : {
        "indices" : [
          "filebeat*"
        ],
        "body" : {
          "query" : {
            "bool" : {
              "must" : {
                "match": {
                   "http.response": 500
                }
              },
              "filter" : {
                "range": {
                  "@timestamp": {
                    "from": "{{ctx.trigger.scheduled_time}}||-10m",
                    "to": "{{ctx.trigger.triggered_time}}"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition" : {
    "compare" : { "ctx.payload.hits.total" : { "gt" : 100 }}
  },
  "actions" : {
    "email_ops" : {
      "email" : {
        "to" : "ops@example.com",
        "subject" : "High 500s detected"
      }
    }
  },
  "metadata": {
    "xpack": {
      "type": "json"
    },
    "name": "http error 500 warning"
  }
}
EOF
}

**Comment by phillbaker** [comment] 2020-12-08 02:55
@Siddhant-Tiwari that's the example from the docs: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/49761c2871079f0412591084009829e4abb7cad5/docs/resources/xpack_watch.md#example-usage

Please include a redacted version of _your_ resource that's failing.

**Comment by Siddhant-Tiwari** [comment] 2020-12-08 02:58
`terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "1.5.0"
    }
  }
}

provider "elasticsearch" {
  sniff = false
  url = "http://127.0.0.1:9200" 
  username = ""
  password = ""
}

resource "elasticsearch_xpack_watch" "GoAnywhereftp-error-watch" {
  watch_id = "Oldman_Chee"
  body = <<EOF
{
  "trigger": {
    "schedule": {
      "interval": "1m"
    }
  },
  "input": {
    "search": {
      "request": {
        "search_type": "query_then_fetch",
        "indices": [
          "integ_goanywhere-chee*"
        ],
        "rest_total_hits_as_int": true,
        "body": {
          "size": 0,
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "log.level": "ERROR"
                  }
                }
              ],
              "filter": {
                "range": {
                  "event.ingested": {
                    "gte": "{{ctx.trigger.scheduled_time}}||-2m",
                    "lte": "{{ctx.trigger.scheduled_time}}",
                    "format": "strict_date_optional_time||epoch_millis"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gt": 0
      }
    }
  },
  "actions": {
    "my-logging-action": {
      "logging": {
        "level": "info",
        "text": "There are {{ctx.payload.hits.total}} documents in your index. Threshold is 0."
      }
    },
    "pagerduty": {
      "webhook": {
        "scheme": "https",
        "host": "events.pagerduty.com",
        "port": 443,
        "method": "post",
        "path": "/generic/2010-04-15/create_event.json",
        "params": {},
        "headers": {
          "Content-type": "application/json"
        },
        "body": "{\"service_key\": \"test\",\"event_type\": \"trigger\",\"description\": \"There are {{ctx.payload.hits.total}} documents in your index. Threshold is 0.\"}"
      }
    }
  }
}
EOF
}`

**Comment by phillbaker** [comment] 2021-01-16 18:54
I'm going to close this as I can't reproduce any issues with a `name` attribute, see tests on CI above. The tests failed because the watch response had additional attributes in it so there was a diff, but it was created.

**Closed by phillbaker** 2021-01-16 18:55 UTC
