### ISSUE TITLE
elasticsearch_composable_index_template misjudges change in ES 7.11.2 for data_stream field

### ISSUE THREAD

**Issue by pinglin** [phillbaker/terraform-provider-elasticsearch#159] opened 2021-03-17 13:02 UTC
When using resource `elasticsearch_composable_index_template` with Elasticsearch 7.11.2, `terraform apply` always says to change these three fields:
```
~ resource "elasticsearch_composable_index_template" "some_index_template" {
      ~ body = jsonencode(
          ~ {
              + composed_of    = []
              + data_stream    = {}
              + version        = 0
                # (3 unchanged elements hidden)
            }
        )
        id   = "<some id>"
        name = "<some name>"
    }
```
, even the previous apply has succeeded.

The `data_stream` field is necessary for indicating the use of data stream for the index template.

**Comment by phillbaker** [comment] 2021-03-19 02:19
Hello, can you please include the following:
* terraform version
* provider version
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by pinglin** [comment] 2021-03-19 22:25
- terraform version
v0.14.8

- provider version
registry.terraform.io/phillbaker/elasticsearch v1.5.4

- redacted version of the terraform resource configuration
The resource configuration is set for index template `"version": 0` all the time.
```
resource "elasticsearch_composable_index_template" "some_index_template" {
    name = "instill-max-size-10gb"
    body = <<EOF
{
    "version": 0,
    ...
}
EOF
}
```

- terraform logs by setting TF_LOG=info
The real log is pretty long. Here is the redacted version for only the relevant piece prettified:
```
2021/03/19 22:10:19 [WARN] Provider "registry.terraform.io/phillbaker/elasticsearch" produced an unexpected new value for elasticsearch_composable_index_template.some_index_template during refresh.
      - .body: was cty.StringVal("{
  \"version\": 0,
  \"priority\": 1000,
  \"data_stream\": {},
  \"index_patterns\": [
    \"max-age-7d-*\"
  ],
  \"template\": {
    \"settings\": {
      \"index\": {
        \"lifecycle\": {
          \"name\": \"max-age-7d-ilm-policy\"
        },
        \"codec\": \"best_compression\"
      }
    }
  }
}
"), but now cty.StringVal("{\"index_patterns\":[\"max-age-7d-*\"],\"priority\":1000,\"template\":{\"settings\":{\"index\":{\"codec\":\"best_compression\",\"lifecycle\":{\"name\":\"max-age-7d-ilm-policy\"}}}}}")
```
It looks like the `data_stream` and `version` fields were not written into the state file. BTW, `composed_of` has been taken away in my codes as it's not useful, but I believe it has the same issue.

**Comment by pinglin** [comment] 2021-05-11 10:39
Yes, exactly. 

> > The data_stream field is necessary for indicating the use of data stream for the index template.
> 
> Can you clarify this? It's necessary to set it to an empty array (and this is what you have in your resource)? But terraform always shows a diff on the empty array?

Yes, exactly. My resource is like:
```
resource "elasticsearch_composable_index_template" "some_index_template" {
  name = "some-name"
  body = <<EOF
{
  "version": 0,
  "priority": 1000,
  "data_stream": {},
  "index_patterns": [
    "some-pattern-*"
  ],
  "template": {
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 1,
      "index": {
        "lifecycle": {
          "name": "some-ilm-policy",
          "rollover_alias": "some-rollover-alias"
        },
        "codec": "best_compression"
      }
    }
  }
}
EOF
}
```

**Comment by phillbaker** [comment] 2021-05-18 03:26
Hi @pinglin, I don't see the `data_stream` attribute documented in ES index templates: https://www.elastic.co/guide/en/elasticsearch/reference/7.11/indices-component-template.html

I will note that the `data_stream` attribute is described when using the older index template endpoint: https://www.elastic.co/guide/en/elasticsearch/reference/master/set-up-a-data-stream.html#create-index-template. This older endpoint maps to the index_template resource: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/index_template.

Can you share a link describing using the `data_stream` attribute in the newer composable templates?

**Comment by phillbaker** [comment] 2021-05-28 01:18
Hello, I'm going to close this issue for now, please see my comment above. If there are further details that show this is a bug/missing feature in the provider, please reopen the issue.

**Comment by pinglin** [comment] 2021-08-12 20:02
Thanks for looking into the issue. Just had a chance to look back on this.

I remember I was able to create an index template for data stream using some hacky way by investigating the raw API via Kibana. Just because in [7.11](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/set-up-a-data-stream.html), that was the official guidance.

It seems that the data stream creation has been properly documented ever since [7.12](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/set-up-a-data-stream.html#create-index-template), so I think this should no longer be an issue.

**Comment by blamarvt** [comment] 2021-09-01 15:13
This still seems to be an issue, and the root cause is that the ES library doesn't return the `data_stream` info when getting index templates: https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/indices_get_index_template.go#L202

Until that's updated we'll continue to get diffs like this on every plan:
```
  # module.event_exporter.elasticsearch_composable_index_template.event_exporter will be updated in-place
  ~ resource "elasticsearch_composable_index_template" "event_exporter" {
      ~ body = jsonencode(
          ~ {
              + data_stream    = {
                  + hidden = false
                }
                # (2 unchanged elements hidden)
            }
        )
        id   = "event-exporter"
        name = "event-exporter"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

That is not to say it doesn't work because it does work just fine (the index template creation just passes through the raw JSON instead of marshaling it into a struct). Just FYI.

**Comment by phillbaker** [comment] 2021-09-17 02:37
Some notes on this:
* the data_stream element isn't really documented well by elasticsearch, the only docs I could find were tangential in the simulate API here: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/indices-simulate-template.html#simulate-template-api-request-body
* in the code it's just a map: https://github.com/elastic/elasticsearch-java/blob/8d34fb3c5889878711d0095d2d5f4a5b37eac80e/java-client/src/main/java/co/elastic/clients/elasticsearch/indices/get_index_template/IndexTemplate.java#L68
* this struct seems to have quite a few more fields: https://github.com/elastic/package-registry/blob/b1056080bef716f5bb0d2a4872de9f067a06507f/util/data_stream.go#L38-L57 seems to match https://github.com/elastic/elasticsearch/blob/9958c3c2fc49a3e253b04e96cfec2e653c39d2e7/client/rest-high-level/src/main/java/org/elasticsearch/client/indices/DataStream.java#L22

**Comment by phillbaker** [comment] 2022-04-03 23:45
Fixed in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/7b976cd8f9d0bde054ffb2fa73dbd3f7d7364dea

**Closed by phillbaker** 2022-04-03 23:45 UTC
Labels: bug
