### ISSUE TITLE
Checking compatibility with Elastic Cloud provider 

### ISSUE THREAD

**Issue by korcadr** [phillbaker/terraform-provider-elasticsearch#176] opened 2021-05-20 15:31 UTC
Hello, I want to use this provider along with Elastic Cloud [https://registry.terraform.io/providers/elastic/ec/latest/docs](url)

I found an issue with having these two provider used in **single terraform run**

Basically this provider configuration requires URL (https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#url) witch is only know after cluster creation with Elastic Cloud provider (terraform apply step). 

After running initial tests it seems this provider accepts outputs from Elastic Cloud resources as input i.e. as module output
```
output "elasticsearch_https_endpoint" {
  depends_on  = [ec_deployment.test_cloud_deployment]
  value       = ec_deployment.main.elasticsearch[0].https_endpoint
  description = "endpoint of newly created cluster at cloud"
}
provider "elasticsearch" {
  url      = module.test_cloud_deployment.elasticsearch_https_endpoint
}
```
But it fails during terraform apply step, unable connecting to cluster.
This code 
```
resource "elasticsearch_opendistro_role" "writer" {
  role_name   = "logs_writer"
  description = "Logs writer role"

  cluster_permissions = ["*"]

  index_permissions {
    index_patterns  = ["logstash-*"]
    allowed_actions = ["write"]
  }
}
resource "elasticsearch_opendistro_user" "writer_logs" {
  username = "app-writer"
  password = "dummy_password"
}
```

produces
```
module.test_elastic_module.elasticsearch_opendistro_role.writer: Creating...
Error: no active connection found: no Elasticsearch node available
  on ../new_provider_test.tf line 2, in resource "elasticsearch_opendistro_role" "writer":
   2: resource "elasticsearch_opendistro_role" "writer" {
Error: no active connection found: no Elasticsearch node available
  on ../new_provider_test.tf line 15, in resource "elasticsearch_opendistro_user" "writer_logs":
  15: resource "elasticsearch_opendistro_user" "writer_logs" {
```

But I am positive Elastic Cloud cluster is created and accessible.

Could you please look into this matter or provide an example of how to use this two providers together?
I think this may be related to provider dependency issue: https://github.com/hashicorp/terraform/issues/2430

**Comment by phillbaker** [comment] 2021-05-28 01:36
Hello, this provider should be compatible with interpolated variables in the provider configuration, please see https://github.com/phillbaker/terraform-provider-elasticsearch/pull/119. 

Specifically this provider is complementary to `terraform-provider-ec`, which is used to manage the underlying cluster in elastic cloud (authentication using APIKEY). 

My understanding is that the [generated user/password](https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment.md#attributes-reference) is used to access the cluster itself using this provider with basic auth, [see the docs here](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#username). It doesn't look like you've provided those values in your configuration.

Can you clarify why you're using opendistro resources on elastic cloud - if you're on elastic cloud, you should have access to xpack.

Please also include:
* terraform version
* provider versions
* elasticsearch version (and opendistro version if relevant)
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by korcadr** [comment] 2021-05-31 14:17
Thank you for looking into this.
I still think there may be an issue with using this two providers. 
I changed from using opendistro to using xpack.

Versions that I am using:
 * Terraform: 0.14.9  
 * elasticsearch provider: 1.5.6
 * elastic cloud provider: 0.1.1
 * elasticsearch version: 7.13.0


I attach log file (TF_LOG=trace) from running `terraform apply`. 
I also attach `minimal_example.zip` holding the code on which I am testing this.
To run this code you will need to create your elastic cloud account (https://cloud.elastic.co/home free trial available) and supply your `api_key` on line 15 in `provider.tf` file. 
[minimal_example.zip](https://github.com/phillbaker/terraform-provider-elasticsearch/files/6570631/minimal_example.zip)
[tf.log](https://github.com/phillbaker/terraform-provider-elasticsearch/files/6570633/tf.log)

This the error when running TF apply command:
```
Error: no active connection found: no Elasticsearch node available
  on elasticsearch_user_roles_xpack.tf line 2, in resource "elasticsearch_xpack_role" "test":
   2: resource "elasticsearch_xpack_role" "test" {

Error: no active connection found: no Elasticsearch node available
  on elasticsearch_user_roles_xpack.tf line 34, in resource "elasticsearch_xpack_user" "test_user":
  34: resource "elasticsearch_xpack_user" "test_user" {
```

**Comment by aceresia** [comment] 2021-06-23 17:11
I was having the same issue.  Turns out it's a certificate issue.  To test try 
`insecure = true`

To use in production I included the digicert global ca in my repo and referenced that file with 

`cacert_file = "${path.module}/gcp-elastic-cloud-com.pem"`

**Comment by phillbaker** [comment] 2021-07-24 17:57
@korcadr can you confirm whether `insecure = true` is working for you?

**Comment by phillbaker** [comment] 2022-01-02 22:15
Sorry for the slow reply here. I took a look at the minimal example and was able to reproduce the issue seen. I'm not sure it's due to the cacert file. I was able to resolve the issue by disabling the `sniff` provider configuration, e.g.:
```
provider "elasticsearch" {
  url      = module.test_elastic_cloud_module.elasticsearch_https_endpoint
  username = module.test_elastic_cloud_module.elasticsearch_username
  password = module.test_elastic_cloud_module.elasticsearch_password
  sniff    = false
}
```

Please note that this option has been changed in the latest versions of 2.0 beta versions of the provider to default to false. I'm going to close this issue, please reopen if you have further questions.

**Closed by phillbaker** 2022-01-02 22:15 UTC
Labels: question
