### ISSUE TITLE
mapping update(adding additional feilds)  forcing  index to be recreated.

### ISSUE THREAD

**Issue by sangeethdba** [phillbaker/terraform-provider-elasticsearch#290] opened 2022-06-29 14:16 UTC
@phillbaker 
```
resource "elasticsearch_index" "test" {
  name               = "terraform-test"
  number_of_shards   = 1
  number_of_replicas = 1
  mappings           = <<EOF
{
  "people": {
    "_all": {
      "enabled": false
    },
    "properties": {
      "email": {
        "type": "text"
      }
    }
  }
}
EOF
}
```
failing when updating this resource with additional fields in mapping.
```
resource "elasticsearch_index" "test" {
  name               = "terraform-test"
  number_of_shards   = 1
  number_of_replicas = 1
  mappings           = <<EOF
{
  "people": {
    "_all": {
      "enabled": false
    },
    "properties": {
      "email": {
        "type": "text"
      },
                         "create_system_cd" : {                       ####new addition####
                           "type" : "text"
                         }
    }
  }
}
EOF
}
```
this change forcing index to me recreated ,

**Comment by phillbaker** [comment] 2022-07-02 16:26
Please see the documentation for the mapping attribute on https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/index:

> mappings (String) A JSON string defining how documents in the index, and the fields they contain, are stored and indexed. To avoid the complexities of field mapping updates, updates of this field are not allowed via this provider. See the upstream [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-put-mapping.html#updating-field-mappings) for more details.

If you'd like to contribute a pull request to handle the issues when mappings may and may not be updated, that'd be great. For now I'm going to close this issue as it appears the provider is working as intended.

**Closed by phillbaker** 2022-07-02 16:26 UTC
