### ISSUE TITLE
Provider "elasticseach" not available for installation

### ISSUE THREAD

**Issue by MIsazaB95** [phillbaker/terraform-provider-elasticsearch#103] opened 2020-10-28 23:40 UTC
I can´t use this provider, do i have to install the binary? or wha can i do?

**Comment by phillbaker** [comment] 2020-10-29 01:12
We'll need more details to determine what the issue is. Can you share the config you're using and any other relevant details?

Maybe related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/97

**Comment by MIsazaB95** [comment] 2020-10-29 13:24
I´m using this configuration:
required_providers {
    elasticsearch = {
      source  = "phillbaker/elasticsearch"
      version = "1.4.4"
    }
  }
But, it does not work, the error is this:
sing previously-installed phillbaker/elasticsearch v1.4.4
Finding latest version of hashicorp/elasticseach...
Error: Failed to install provider

Error while installing hashicorp/elasticseach: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/elasticseach

**Comment by phillbaker** [comment] 2020-10-30 11:52
What version of terraform are you using? The registry is only supported on terraform >= 0.13.

**Comment by phillbaker** [comment] 2020-11-02 23:38
@MIsazaB95 can you provide an update here, otherwise I'll close this issue as having been resolved.

**Comment by MIsazaB95** [comment] 2020-11-03 20:55
issue resolved

**Closed** 2020-11-03 20:55 UTC

**Comment by vijay-singh** [comment] 2020-12-15 20:45
What was the resolution? Having a similar issue

**Comment by phillbaker** [comment] 2020-12-16 02:40
@vijay-singh I've only seen this issue when using a terraform version less than 13.x. Since the registry is only supported on >= 13.x, please make sure you're using a version that supports it.

Otherwise please open a new issue including the following:
* terraform version
* provider version
* elasticsearch version
* redacted version of the terraform resource configuration
* terraform logs by setting `[TF_LOG=info](https://www.terraform.io/docs/internals/debugging.html)`

**Comment by vijay-singh** [comment] 2020-12-16 16:41
For me, solved by following the steps detailed here: https://discuss.hashicorp.com/t/upgrade-to-0-13-fails-looking-for-invalid-custom-provider/13770

I had a `required_providers` block in my root module, but also needed to add it to the submodule that was using this provider.
