### ISSUE TITLE
Plug-in Failed 

### ISSUE THREAD

**Issue by colegulledge** [phillbaker/terraform-provider-elasticsearch#246] opened 2022-02-03 20:41 UTC
Not really an issue, but in search of help.. my first time using terraform lol. 

I can init, validate, plan, etc successfully. But when I go to apply any of the resources I get a “plugin failed”… any ideas? 

Thanks

**Comment by phillbaker** [comment] 2022-02-04 02:17
Hello, this seems like a duplicate of #244

**Comment by phillbaker** [comment] 2022-02-09 02:51
As followup, please provide the following:
* terraform version
* provider version
* elasticsearch version (and opendistro version if relevant)
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Closed** 2022-02-12 21:31 UTC
