### ISSUE TITLE
Error: ElasticSearch version  is older than 6.0.0 and is not supported.

### ISSUE THREAD

**Issue by leonid-granulate** [phillbaker/terraform-provider-elasticsearch#232] opened 2021-11-21 12:26 UTC
Hi,
Here is my setup

- Elasticsearch version  = 7.15.1
- Provider version = 2.0.0-beta.2
- Terraform version = 0.14.5

provider configuration:
```
provider "elasticsearch" {
  url = "https://127.0.0.1:9200/&sniff=false"
  username = "rightusername"
  password = "rightpassword"
  insecure = true
  healthcheck = false
  sniff = false
}
```
I'm using ssh port forwarding to remote server

After running `terraform apply` 

I get the following message:
`Error: ElasticSearch version  is older than 6.0.0 and is not supported.`

If i specify the version i get the following:
`Error: Malformed version:`

**Comment by phillbaker** [comment] 2021-11-22 00:40
Hello, this seems similar to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/113. I don't believe anything changed that would break this behavior.

Can you confirm that you can `curl` the cluster on `https://127.0.0.1:9200`? Why are you appending `&sniff=false`?

**Comment by phillbaker** [comment] 2021-11-22 00:41
Please also include terraform logs by setting [`TF_LOG=trace`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by leonid-granulate** [comment] 2021-11-22 08:30
> Hello, this seems similar to #113. I don't believe anything changed that would break this behavior.
> 
> Can you confirm that you can `curl` the cluster on `https://127.0.0.1:9200`? Why are you appending `&sniff=false`?

Yes, `curl` returns me a correct response, i'm using `&sniff=false` because my elastic search cluster is under private network, see [this](https://stackoverflow.com/questions/61455272/cannot-connect-to-elastic-search-no-active-connection-found-no-elasticsearch#:~:text=This%20can%20happen%20(NOTE%3A%20we%20had%20chat%20with%20OP%20where%20we%20debugged%20issue)%20also%20when%20your%20cluster%20is%20configured%20with%20private%20IPs%20(so%20in%20/_nodes%20API%20output%20you%20see%20private%20and%20not%20public%20IPs).)

**Comment by leonid-granulate** [comment] 2021-11-22 08:56
Ok, i realized that `?sniff=false` was wrong parameter, and elasticsearch return 400 when i pass it, but anyway i can't connect to cluster, here is my curl response:
```
❯ curl -k -XGET 'https://user:password@localhost:9200'
{
  "name" : "name",
  "cluster_name" : "cluster",
  "cluster_uuid" : "id",
  "version" : {
    "number" : "7.15.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "83c34f456ae29d60e94d886e455e6a3409bba9ed",
    "build_date" : "2021-10-07T21:56:19.031608185Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
`TF_LOG=trace terraform apply` response:
```
elasticsearch_kibana_alert.test: Creating...
2021/11/22 10:53:00 [DEBUG] EvalApply: ProviderMeta config value set
2021/11/22 10:53:00 [DEBUG] elasticsearch_kibana_alert.test: applying the planned Create change
2021/11/22 10:53:00 [TRACE] GRPCProvider: ApplyResourceChange
2021/11/22 10:53:00 [DEBUG] elasticsearch_kibana_alert.test: apply errored, but we're indicating that via the Error pointer rather than returning it: no active connection found: no Elasticsearch node available
2021/11/22 10:53:00 [TRACE] EvalMaybeTainted: elasticsearch_kibana_alert.test encountered an error during creation, so it is now marked as tainted
2021/11/22 10:53:00 [TRACE] EvalWriteState: removing state object for elasticsearch_kibana_alert.test
2021/11/22 10:53:00 [TRACE] EvalApplyProvisioners: elasticsearch_kibana_alert.test has no state, so skipping provisioners
2021/11/22 10:53:00 [TRACE] EvalMaybeTainted: elasticsearch_kibana_alert.test encountered an error during creation, so it is now marked as tainted
2021/11/22 10:53:00 [TRACE] EvalWriteState: removing state object for elasticsearch_kibana_alert.test
2021/11/22 10:53:00 [TRACE] vertex "elasticsearch_kibana_alert.test": visit complete
2021/11/22 10:53:00 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/11/22 10:53:00 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/phillbaker/elasticsearch\"] (close)" errored, so skipping
2021/11/22 10:53:00 [TRACE] dag/walk: upstream of "root" errored, so skipping

Error: no active connection found: no Elasticsearch node available


2021-11-22T10:53:00.574+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-11-22T10:53:00.575+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/phillbaker/elasticsearch/2.0.0-beta.2/darwin_amd64/terraform-provider-elasticsearch_v2.0.0-beta.2 pid=17960
2021-11-22T10:53:00.575+0200 [DEBUG] plugin: plugin exited
```

**Comment by phillbaker** [comment] 2022-01-03 00:26
Hi @leonid-granulate, I can't reproduce this. I've set up a jumpbox with a VPC-only ES cluster on AWS. Tunneling through the jumpbox to the cluster from my local machine allows me to run terraform against localhost.

Unless you can provide additional details about your set up so that it can be reproduced, I'm going to close this issue out.

**Closed** 2022-01-04 13:59 UTC

**Comment by harrowkalsi55** [comment] 2023-01-09 06:24
I got the same error
I get the following message:

│ Error: ElasticSearch version  is older than 6.0.0 and is not supported, flavor: 0.


But in mycase, this is misleading error actual issue was that, I was using wrong password for elastic,
So make sure you have configured elastic provider with correct credentials.

**Comment by NathanBaulch** [comment] 2024-09-04 04:40
CI on this repo itself is now returning this error. The double space in:
```
Error: ElasticSearch version  is older than 6.0.0 and is not supported.
                            /\
```
suggests that the automation was unable to determine the version (`ProviderConf.esVersion` is empty string).
